import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import StarsBackground from "./components/StarsBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <div className="relative">
          <StarsBackground />
          <div className="relative z-10">
            <header>
              <Navbar />
            </header>
            {/* Layout UI */}
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
